### PR TITLE
added sun to board page

### LINKED ISSUE #89: Add Sun to Board Page
image

### PR DESCRIPTION
**Pull request by zalam007**

### CODE REVIEW

**Comment by seanquiambao** [comment]
please remember to link your issue and assign me as a reviewer.

also can you take a screen shot of the board page, just so i can compare what you see vs what i see?

**Comment by zalam007** [comment]
s

**Review by seanquiambao — CHANGES_REQUESTED** [review]
image

match the position of the sun to the figma file design. it should be placed on the bottom right.

**Comment by zalam007** [comment]
ns

made changes, should be repushed

**Review by seanquiambao — APPROVED** [review]

**Pull request merged**
